version: '3'

# Each service runs in a separate container
services:
# the name of the service
    express-service:
            # shorthand name for the container
            container_name: express
            # build path to the Dockerfile
            build: ./
            # create a bind mount so local changes show up in the container
            # for development (lots of changes - restarting the container would be slow)
            volumes:
                - ./:/app:Z 
            # map the ports <outside container>:<inside container>
            ports:
                - "8000:8000"
            # Override the entrypoint in the Dockerfile
            command: ["nodemon", "express.js"]

    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
            POSTGRES_DB: dad-joke-reviews
        ports:
            - "5432:5432"
        volumes:
        # copy the sql script to create tables
        - ./init/migrate_seed.sql:/docker-entrypoint-initdb.d/migrate_seed.sql

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: moneymason0@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-db
   
volumes:
  pgadmin-data: